### PR TITLE
release 0.4 for ATutor 2.2.2

### PR DESCRIPTION
**Pull request by sudwebdesign**
New feature : export directly from HTML and css with HTML2PDF class

### CODE REVIEW

**Comment by atutor** [comment]
in the  b78ac96 commit, you should replace queryDBresult with queryDB() and pass the  variables in through it so they get filtered properly to prevent a vulnerability. 

$sql    = "SELECT \* FROM ".TABLE_PREFIX."content WHERE content_id=$_GET[cid]";
$result = queryDBresult($sql);

to something like this

$sql    = "SELECT \* FROM %scontent WHERE content_id=%d";
$content_rows = queryDB($sql, array(TABLE_PREFIX, $_GET[cid]));
(also for the query in side_menu.inc.php)

This will validate the values ($_GET['cid'])  as a digit (%d) before inserted into the DB, and prevent potential sql injection. You may also want to scan through the other files in the module for other queries. The module has not been updated in a long time, so there may be other vulnerabilities in it.

**Comment by sudwebdesign** [comment]
prevent potential sql injection Fixed in [66c09ce](https://github.com/atutor/pdf_converter/pull/1/commits/66c09cef6894e7be29d16a0f52d82bb22566892d)

thanks Greg

**Comment by sudwebdesign** [comment]
in this [comment](https://github.com/atutor/pdf_converter/pull/1#commitcomment-18903078) the course is deserved by AContent (i never tested this case) but in sql query on pdf_converter.php file no grab url of content (Now, Only title & text).

curious comportment
where found one course url, cartridge or SCORM for import in my AContent site and testing locally

With content course inside ATutor work fine.

**Comment by atutor** [comment]
Yes, you're right.  It exports local ATutor pages correctly.

There are some sample cartridges at:
http://www.atutor.ca/atutor/docs/howto.php

**Pull request merged**
